[SERVICE]
    Parsers_File   conf\parsers.conf
    Parsers_File   conf\parse_custom.conf

[INPUT]
    Name               syslog
    Mode               udp
    Listen             0.0.0.0
    Port               1517
    Parser             syslog-passthrough
    Tag                syslog
    Source_Address_Key hostIp

[FILTER]
    Name    lua
    Match   syslog
    script  conf\enrich_syslog.lua
    call    enrich

[OUTPUT]
    Name   stdout
    Match  *

[OUTPUT]
    Name   file
    Path   data\
    Match  *
    File   1.logs
    Format Plain

[OUTPUT]
    Name   es
    Match  *
    Port   9200
    Index  ScribblerCurrent
    Suppress_Type_Name On