[SERVICE]
    Flush          1
    Daemon         Off
    Log_Level      info
    Parsers_File   parsers.conf
    Parsers_File   parse_custom.conf

[INPUT]
    Name               syslog
    Mode               udp
    Listen             0.0.0.0
    Port               1517
    Parser             syslog-passthrough
    Tag                syslog
    Source_Address_Key hostIp

[INPUT]
    Name               syslog
    Mode               tcp
    Listen             0.0.0.0
    Port               1518
    Parser             syslog-passthrough
    Tag                syslog
    Source_Address_Key hostIp
    Format             newline

[INPUT]
    Name               syslog
    Mode               tcp
    Listen             0.0.0.0
    Port               1519
    Parser             syslog-passthrough
    Tag                syslog
    Format             octet_counting
    Tls                on
    tls.crt_file       C:\Users\DhanudharsanDE\Downloads\publickey.crt
    tls.key_file       C:\Users\DhanudharsanDE\Downloads\privatekey.key
    tls.key_passwd     pass
    
    # 2. KEEP THESE: Compatibility ranges
    tls.min_version    TLSv1.1
    tls.max_version    TLSv1.3
    tls.verify         off
    #tls.verify_client_cert on

    
[OUTPUT]
    Name   file
    Match  syslog
    Path   data\
    File   raw_messages.log
    Format Plain

#[INPUT]
#    Name               syslog
#    Mode               tcp
#    Listen             0.0.0.0
#    Port               1519
#    Parser             syslog-passthrough
#    Tag                syslog
#    Source_Address_Key hostIp
#    Format             octet_counting

[FILTER]
    Name    lua
    Match   syslog
    script  enrich_syslog.lua
    call    enrich
    
[FILTER]
    Name          rewrite_tag
    Match         syslog
    Rule          $rawforward .* syslog.forward true
    Emitter_Name  syslog_forward_emitter

[FILTER]
    Name       record_modifier
    Match      syslog
    Remove_key rawforward

[OUTPUT]
    Name   stdout
    Match  syslog

#[OUTPUT]
#    Name   file
#    Match  *
#    Path   data\
#    File   syslog_parsed.log
#    Format Plain

[OUTPUT]
    Name              es
    Match             syslog
    Host              127.0.0.1
    Port              9200
    Index             ScribblerCurrent
    Suppress_Type_Name On


[OUTPUT]
    Name             tcp
    Match            syslog.forward
    Host             10.10.1.92
    Port             1514
    raw_message_key  $rawforward
    Retry_Limit      no_limits
    net.keepalive    on
